#  A simple script to integrate the json snippets generated by the 
#  Strawberry Perl build system into the releases.json file.
#
#  The snippets currently need hand-editing to update the URLs
#  but that is difficult to automate at the moment.
#  
#  Call as 
#  perl integrate_json_snippets.pl snippet1.json snippet2.json


use 5.010;
use strict;
use warnings;

use Cpanel::JSON::XS;
use File::Copy;

my @snippets = @ARGV;

my $json_file = 'releases.json';

copy($json_file, "${json_file}.bk") or die "Copy failed: $!";

open my $json_fh, $json_file or die $!;

my $data = do {local $/ = undef; <$json_fh>};

close $json_fh;

my $struct = decode_json $data;

foreach my $snippet_file (@snippets) {
    open my $fh, $snippet_file or die $!;
    my $snippet_data = do {local $/ = undef; <$fh>};
    close $fh;
    
    #  make these conform
    $snippet_data =~ s/"portable_zip"/"portable"/ms;
    $snippet_data =~ s/"pdl_zip"/"portable"/ms;
    $snippet_data =~ s{(release-notes/)strawberry-perl-}{$1}ms;
    
    my $snippet = decode_json $snippet_data;
    push @$struct, $snippet;
}

#  Arrange in descending order by date.
#  Dates are formatted as YYYY-MM-DD strings so cmp is all that is needed here.
my $sorted = [sort {$b->{date} cmp $a->{date}} @$struct];

open my $ofh, '>', $json_file or die $!;

my $updated_json 
  = Cpanel::JSON::XS->new->canonical->pretty->space_before(0)->encode ($sorted);

print {$ofh} $updated_json;

close $json_fh;
